apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - mongodb.yaml
  - bookstore-backend.yaml
  - bookstore-frontend.yaml
  - hpa.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: ns-bookstoreapp
    setRoleBindingSubjects: null
    unsetOnly: false
    fieldSpecs:
    - path: metadata/namespace
      create: true
      kind: Deployment
      group: apps
    - path: metadata/namespace
      create: true
      kind: Service
      group: ""
    - path: metadata/namespace
      create: true
      kind: ConfigMap
      group: ""
    - path: metadata/namespace
      create: true
      kind: Secret
      group: ""
    - path: metadata/namespace
      create: true
      kind: Ingress
      group: networking.k8s.io
    - path: metadata/namespace
      create: true
      kind: HorizontalPodAutoscaler
      group: autoscaling
    - path: metadata/namespace
      create: true
      kind: ServiceAccount
      group: ""
    - path: metadata/namespace
      create: true
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
    - path: metadata/namespace
      create: true
      kind: RoleBinding
      group: rbac.authorization.k8s.io